# redis from: https://hub.docker.com/_/redis
---
- name: Set overcommit_memory to 1 for redis
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: true

- name: Start redis docker container
  community.docker.docker_container:
    name: redis
    image: redis:alpine
    networks:
      - name: macvlan333
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
