# install Deluge torrent client
# https://hub.docker.com/r/linuxserver/deluge

- name: Create a volume for deluge config
  docker_volume:
    name: config_deluge

- name: create deluge data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0775
  with_items:
    - "{{ docker_data_location }}/deluge/watch"

- name: setup Deluge docker container
  docker_container:
    name: deluge
    image: linuxserver/deluge:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.deluge }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.deluge }}"
    purge_networks: yes
    volumes:
      - "config_deluge:/config"
      - "/data/media:/data"
      - "{{ docker_data_location }}/deluge/watch:/watch"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: yes
    pull: true
    labels:
      traefik.http.routers.deluge.tls: "true"
      traefik.http.routers.deluge.tls.certresolver: "le"
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
