# install Deluge torrent client
# https://hub.docker.com/r/linuxserver/deluge

- name: Create a volume for deluge config
  docker_volume:
    name: "{{ item }}"
  loop: 
    - config_deluge
    - data_deluge_watch

- name: set permissions on docker volume
  file:
    path: /data/docker/docker/volumes/data_deluge_watch/_data
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: setup Deluge docker container
  docker_container:
    name: deluge
    image: linuxserver/deluge:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.deluge }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.deluge }}"
    purge_networks: yes
    volumes:
      - "config_deluge:/config"
      - "/data/media:/data"
      - "data_deluge_watch:/watch"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: yes
    pull: true
    labels:
      traefik.http.routers.deluge.tls: "true"
      traefik.http.routers.deluge.tls.certresolver: "le"
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
