# install Deluge torrent client
# https://hub.docker.com/r/linuxserver/deluge
---
- name: Create a volume for deluge config
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - config_deluge
    - data_deluge_watch

- name: Set permissions on docker volume
  ansible.builtin.file:
    path: /data/docker/docker/volumes/data_deluge_watch/_data
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Setup Deluge docker container
  community.docker.docker_container:
    name: deluge
    image: linuxserver/deluge:latest
    networks:
      - name: macvlan333
        # ipv4_address: "{{ docker.network.ipv4_prefix }}{{ docker.network.hosts.deluge }}"
        # ipv6_address: "{{ docker.network.ipv6_prefix }}{{ docker.network.hosts.deluge }}"
    volumes:
      - "config_deluge:/config"
      - "/data/media:/media"
      - "data_deluge_watch:/watch"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.deluge.tls: "true"
      traefik.http.routers.deluge.tls.certresolver: "le"
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
