- name: create postgres directory
  file:
    path: /data/netbox/postgres
    state: directory
    mode: 0700
    owner: 70
    group: 70

- name: setup postgres
  docker_container:
    name: postgres
    image: postgres:11-alpine
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.postgres }}"
    purge_networks: yes
    volumes:
      - "/data/netbox/postgres:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
