- name: create nginx directories
  file:
    path: "{{ docker_config_location }}/nginx"
    state: directory
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ docker_config_location }}/nginx/nginx.conf"
    mode: 0644
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Start nginx docker container
  docker_container:
    name: nginx
    image: nginx:alpine
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.nginx }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.nginx }}"
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.nginx.rule: "Host(`frai.se`)"
      traefik.http.routers.nginx.tls: "true"
      traefik.http.routers.nginx.tls.certresolver: "le"
      traefik.http.services.nginx.loadbalancer.server.port: "8080"
