---
- name: Create nginx directories
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/nginx"
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ docker.dir.config }}/nginx/nginx.conf"
    mode: "0644"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Start nginx docker container
  community.docker.docker_container:
    name: nginx
    image: nginx:alpine
    networks:
      - name: services
    dns_servers:
      - "{{ dns_servers.adguard.dco.ipv6 }}"
      - "{{ dns_servers.adguard.dco.ip }}"
      - "{{ dns_servers.adguard.home.ipv6 }}"
      - "{{ dns_servers.adguard.home.ip }}"
    volumes:
      - "{{ docker.dir.config }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.nginx.rule: "Host(`frai.se`)"
      traefik.http.routers.nginx.tls: "true"
      traefik.http.routers.nginx.tls.certresolver: "le"
      traefik.http.services.nginx.loadbalancer.server.port: "8080"
