---
driver:
  name: docker

ansible:
  cfg:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles

scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

platforms:
  - name: photon-instance
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    host_vars:
      photon-instance:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
