- name: restart synapse container
  docker_container:
    name: synapse
    state: started
    restart: yes

- name: restart telegram container
  docker_container:
    name: mautrix-telegram
    state: started
    restart: yes

- name: restart whatsapp container
  docker_container:
    name: mautrix-whatsapp
    state: started
    restart: yes
