---
interfaces:
  - name: ens18
    description: MAIN
    mode: static
    addresses:
      - ip: 10.10.48.36/27
        gateway: 10.10.48.33
      - ip: 2a12:4946:4002:1000::4/64
        gateway: 2a12:4946:4002:1000::1
