# setup openvpn with a docker container
# container from: http://docs.grafana.org/installation/docker/

- name: create grafana config directory
  file:
    path: /data/grafana/plugins
    state: directory
    mode: 0755
    owner: root
    group: data
    recurse: yes

- name: setup grafana docker container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.grafana }}"
    purge_networks: yes
    volumes:
      - "/data/grafana:/var/lib/grafana"
    env:
      GF_SERVER_ROOT_URL: "https://grafana.frai.se"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_INSTALL_PLUGINS: "raintank-worldping-app"
    restart: yes
    state: started
    restart_policy: always
    pull: true
    user: 0:0
    labels:
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: "le"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
