# setup openvpn with a docker container
# container from: http://docs.grafana.org/installation/docker/
---
- name: Create a volume for grafana content
  community.docker.docker_volume:
    name: data_grafana

- name: Setup grafana docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    networks:
      - name: macvlan333
    volumes:
      - "data_grafana:/var/lib/grafana"
    env:
      GF_SERVER_ROOT_URL: "https://grafana.frai.se"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    restart: true
    state: started
    restart_policy: always
    pull: true
    user: 0:0
    labels:
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: "le"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
