# setup openvpn with a docker container
# container from: http://docs.grafana.org/installation/docker/

- name: Create a volume for grafana content
  docker_volume:
    name: data_grafana

- name: setup grafana docker container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.grafana }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.grafana }}"
    purge_networks: yes
    volumes:
      - "data_grafana:/var/lib/grafana"
    env:
      GF_SERVER_ROOT_URL: "https://grafana.frai.se"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    restart: yes
    state: started
    restart_policy: always
    pull: true
    user: 0:0
    labels:
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: "le"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
