all:
  children:
    servers:
      children:
        compute:
          hosts:
            captain:
              ansible_python_interpreter: /usr/bin/python3
              ansible_host: 172.16.33.8
        proxmox:
          hosts: 
            falcon:
              ansible_python_interpreter: /usr/bin/python3
              ansible_host: 172.16.33.7
        unraid:
          hosts: 
            kang:
              ansible_python_interpreter: /usr/bin/python3
              ansible_host: 172.16.33.6
              ansible_user: root
    routers:
      children:
        mikrotik:
          hosts:
            ironman:
              ansible_python_interpreter: /usr/bin/python3
              ansible_host: 172.16.33.1
