- name: create teamspeak data directory
  file:
    path: /data/teamspeak
    state: directory
    mode: 0755

- name: setup teamspeak docker container
  docker_container:
    name: teamspeak
    image: teamspeak:latest
    network_mode: bridge
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    volumes:
      - "/data/teamspeak:/var/ts3server/"
    networks:
      - name: fraise_network
        ipv4_address: "172.16.34.14" # TODO: archive
    env:
      TS3SERVER_LICENSE: accept
    restart: yes
    state: started
    pull: true
