---
groups:
  - name: networking.rules
    rules:
      - alert: BGP Session Offline
        expr: frr_bgp_peer_state{safi="unicast"} == 0
        for: 10m
        annotations:
          summary: "IDLE - {{ $labels.peer }}:AS{{ $labels.peer_as }} - {{ $labels.peer_desc }}"

      - alert: Interface offline
        expr: ifOperStatus{ifDescr!~".*LOCAL_MGMT", ifDescr!~".*NOMON", device_role!="switch"} != 1 and ifAdminStatus==1
        for: 10m

      - alert: High CPU Usage
        expr: (avg by (node_name) (hrProcessorLoad)) > 75
        for: 5m
