# setup watchtower with a docker container
# container from: https://www.portainer.io/installation/

- name: setup watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    command: --cleanup --interval 7200
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: yes
    state: started
    restart_policy: always
    pull: true
    labels:
      traefik.enable: "false"