---
node_exporter_version: 1.6.1
local_password_location: ~/ansible_password_file

dns:
  servers:
    - 1.1.1.1
    - 1.0.0.1

admin_users:
  - user: gianni
    key: StubbeGianni
    name: "Gianni Stubbe"
    ssh_key: "https://github.com/33Fraise33.keys"
