---
- name: Set unbound lancache directory permissions
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/unbound/lancache"
    state: directory
    mode: "0755"

- name: Get uklans github repo  # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/uklans/cache-domains
    dest: "{{ docker.dir.config }}/unbound/lancache/"
    force: true

- name: Install jq package for cache domain script
  ansible.builtin.apt:
    name:
      - jq

- name: Copy lancache template files
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "{{ docker.dir.config }}/unbound/lancache/scripts/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - name: config.json
      mode: "0644"
    - name: copy-files.sh
      mode: "0755"

- name: Create new lancache domains at midnight
  ansible.builtin.cron:
    name: "update lancache domains"
    minute: "15"
    hour: "4"
    job: " {{ docker.dir.config }}/unbound/lancache/scripts/copy-files.sh"
