# setup unbound with a docker container
# container from: https://github.com/klutchell/unbound-docker
---
- name: Create unbound config directories
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/unbound"
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Import lancache task
  ansible.builtin.import_tasks: lancache-dns.yml
  tags: lancache

# config from https://github.com/klutchell/unbound-docker/blob/main/rootfs_overlay/etc/unbound/unbound.conf
- name: Copy config file
  ansible.builtin.copy:
    src: unbound.conf
    dest: "{{ docker.dir.config }}/unbound/unbound.conf"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: "0755"

- name: Setup unbound docker container
  community.docker.docker_container:
    name: unbound
    image: mvance/unbound:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker.network.ipv4_prefix }}{{ docker.network.hosts.unbound }}"
        ipv6_address: "{{ docker.network.ipv6_prefix }}{{ docker.network.hosts.unbound }}"
    volumes:
      - "{{ docker.dir.config }}/unbound/lancache/scripts/output/unbound/:/opt/unbound/etc/unbound/custom.conf.d/:ro"
      - "{{ docker.dir.config }}/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
