# install ddclient
# https://hub.docker.com/r/linuxserver/ddclient
---
- name: Create ddclient config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: "0775"
  loop:
    - "{{ docker.dir.config }}/ddclient"

- name: Copy ddclient config
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: "{{ docker.dir.config }}/ddclient/ddclient.conf"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: "0664"

- name: Setup ddclient docker container
  community.docker.docker_container:
    name: ddclient
    image: linuxserver/ddclient:latest
    networks:
      - name: macvlan333
    volumes:
      - "{{ docker.dir.config }}/ddclient:/config"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.enable: "false"
