# setup wordpress with a docker container
# container from: https://hub.docker.com/_/wordpress
---
- name: Setup mariadb
  ansible.builtin.import_tasks: mariadb.yml
  tags: mariadb

- name: Create a volume for wordpress content
  community.docker.docker_volume:
    name: data_wordpress

- name: Create wordpress config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/wordpress"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy wordpress ini file
  ansible.builtin.copy:
    src: wordpress.ini
    dest: "{{ docker.dir.config }}/wordpress/wordpress.ini"
    mode: "0644"
    owner: root
    group: root

- name: Setup wordpress docker container
  community.docker.docker_container:
    name: wordpress
    image: wordpress:latest
    networks:
      - name: services
    env:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_user_password }}"
    volumes:
      - "data_wordpress:/var/www/html/wp-content"
      - "{{ docker.dir.config }}/wordpress/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini:ro"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.wordpress.rule: "Host(`unitix.be`)"
      traefik.http.routers.wordpress.tls: "true"
      traefik.http.routers.wordpress.tls.certresolver: "le"
      traefik.http.services.wordpress.loadbalancer.server.port: "80"
