# setup wordpress with a docker container
# container from: https://hub.docker.com/_/wordpress

- import_tasks: mariadb.yml
  tags: mariadb

- name: Create a volume for wordpress content
  docker_volume:
    name: data_wordpress

- name: create wordpress config directory
  file:
    path: "{{ docker_config_location }}/wordpress"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy wordpress ini file
  copy:
    src: wordpress.ini
    dest: "{{ docker_config_location }}/wordpress/wordpress.ini"
    mode: 0644
    owner: root
    group: root

- name: setup wordpress docker container
  docker_container:
    name: wordpress
    image: wordpress:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.wordpress }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.wordpress }}"
    purge_networks: yes
    env:
      WORDPRESS_DB_HOST: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.mariadb }}"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_user_password }}"
    volumes:
      - "data_wordpress:/var/www/html/wp-content"
      - "{{ docker_config_location }}/wordpress/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini:ro"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.wordpress.rule: "Host(`unitix.be`)"
      traefik.http.routers.wordpress.tls: "true"
      traefik.http.routers.wordpress.tls.certresolver: "le"
      traefik.http.services.wordpress.loadbalancer.server.port: "80"
