---
# backup and restore:
# sudo docker exec -it mariadb /bin/bash
# mysqldump -uroot -p --all-databases > mariadbbackup.sql
# mysql -uroot -p < mariadbbackup.sql

- name: Create a volume for mariadb data
  community.docker.docker_volume:
    name: data_mariadb

- name: Setup mariadb docker container
  community.docker.docker_container:
    name: mariadb
    image: mariadb:latest
    networks:
      - name: macvlan333
    volumes:
      - "data_mariadb:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "{{ mysql_user_password }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
