# install Guacamole Remote access software
# http://guacamole.apache.org/doc/gug/guacamole-docker.html

- name: setup guacd docker container
  docker_container:
    name: guacd
    image: guacamole/guacd:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.guacd }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.guacd }}"
    purge_networks: yes
    state: started
    restart_policy: always
    restart: yes
    pull: true

- name: Create a new database with name "guacamole_db"
  community.general.postgresql_db:
    name: guacamole_db
    login_host: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0


# - name: Initialize database
#   shell: |
#      docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
#      docker cp ./initdb.sql postgres:/docker-entrypoint-initdb.d/initdb.sql
#      docker exec -u postgres postgres psql guacamole_db {{ postgres_user }} -f /docker-entrypoint-initdb.d/initdb.sql
#      rm -rf ./initdb.sql

- name: setup guacamole docker container
  docker_container:
    name: guacamole
    image: guacamole/guacamole:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.guacamole }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.guacamole }}"
    purge_networks: yes
    env:
      GUACD_HOSTNAME: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.guacd }}"
      GUACD_PORT: "4822"
      POSTGRES_DATABASE: "guacamole_db"
      POSTGRES_HOSTNAME: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    state: started
    restart_policy: always
    restart: yes
    pull: true
    labels:
      traefik.http.routers.guacamole.tls: "true"
      traefik.http.routers.guacamole.tls.certresolver: "le"
      traefik.http.services.guacamole.loadbalancer.server.port: "8080"
