# setup accserver with a docker container
# container from: https://github.com/assetto-corsa-web/accweb

- name: create accserver config directory
  file:
    path: /data/accserver
    state: directory
    mode: 0755
    owner: gianni
    group: data
    recurse: yes

- name: copy server exe to server
  copy:
    src: accServer.exe
    dest: /data/accserver/accServer.exe
    mode: 0755
    owner: gianni
    group: data

- name: setup accserver docker container
  docker_container:
    name: accserver
    image: kugel/accweb:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.accserver }}"
    purge_networks: yes
    volumes:
      - "/data/accserver:/accserver"
    env:
      ACCWEB_HOST: 0.0.0.0:8080
      ACCWEB_ADMIN_PASSWORD: "{{ admin_password }}"
      ACCWEB_MOD_PASSWORD: "{{ mod_password }}"
      ACCWEB_RO_PASSWORD: ro
      ACCWEB_LOGLEVEL: info
      ACCWEB_CORS: "*"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.accserver.rule: "Host(`accserver.frai.se`)"
      traefik.http.routers.accserver.tls: "true"
      traefik.http.routers.accserver.tls.certresolver: "le"
      traefik.http.services.accserver.loadbalancer.server.port: "8080"
