# Docker Image from: https://hub.docker.com/r/coturn/coturn

- name: create coturn directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    recurse: yes
  with_items:
    - "{{ docker_config_location }}/coturn"

- name: copy coturn config
  template:
    src: turnserver.conf.j2
    dest: "{{ docker_config_location }}/coturn/turnserver.conf"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0700
  tags: config

- name: Start coturn docker container
  docker_container:
    name: coturn
    image: coturn/coturn:alpine
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.coturn}}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.coturn}}"
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/coturn/turnserver.conf:/etc/coturn/turnserver.conf"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
