# https://github.com/tulir/mautrix-telegram

- name: create bridge directory
  file:
    path: "{{ docker_config_location }}/matrix-bridges/mautrix-telegram"
    state: directory
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    recurse: yes

- name: Copy telegram config template to server
  template:
    src: telegram.yaml.j2
    dest: "{{ docker_config_location }}/matrix-bridges/mautrix-telegram/config.yaml"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0755
  tags: config

- name: Create a new database with name "telegram"
  community.general.postgresql_db:
    name: telegram
    login_host: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0

- name: Start telegram bridge docker container (create config file)
  docker_container:
    name: mautrix-telegram
    image: dock.mau.dev/mautrix/telegram:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.mautrix_telegram}}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.mautrix_telegram}}"
    volumes:
      - "{{ docker_config_location }}/matrix-bridges/mautrix-telegram:/data"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.enable: "false"
