# https://github.com/tulir/mautrix-whatsapp/wiki

- name: create bridge directory
  file:
    path: "{{ docker_config_location }}/matrix-bridges/mautrix-whatsapp"
    state: directory
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    recurse: yes

- name: Copy whatsapp config template to server
  template:
    src: whatsapp.yaml.j2
    dest: "{{ docker_config_location }}/matrix-bridges/mautrix-whatsapp/config.yaml"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0755
  tags: config

- name: Create a new database with name "whatsapp"
  community.general.postgresql_db:
    name: whatsapp
    login_host: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0

- name: Start whatsapp bridge docker container
  docker_container:
    name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.mautrix_whatsapp }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.mautrix_whatsapp }}"
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/matrix-bridges/mautrix-whatsapp:/data"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    state: started
    restart: yes
    restart_policy: always
    pull: true
    labels:
      traefik.enable: "false"
