# setup ghost with a docker container
# container from: https://www.portainer.io/installation/ # TODO

- name: create ghost config directory
  file:
    path: /data/ghost
    state: directory
    mode: 0755
    owner: root
    group: data
    recurse: yes

- name: setup ghost docker container
  docker_container:
    name: ghost
    image: library/ghost:alpine
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ghost }}"
    purge_networks: yes
    volumes:
      - "/data/ghost:/var/lib/ghost/content"
    env:
      url: "https://ghost.frai.se"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.ghost.rule: "Host(`ghost.frai.se`)"
      traefik.http.routers.ghost.tls: "true"
      traefik.http.routers.ghost.tls.certresolver: "le"
      traefik.http.services.ghost.loadbalancer.server.port: "2368"
