# container from: https://hub.docker.com/r/adguard/adguardhome

- name: Create a volume for adguard data
  docker_volume:
    name: data_adguard


- name: create adguard config directory
  file:
    path: "{{ docker_config_location }}/adguard"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy config file
  template: 
    src: AdGuardHome.yaml.j2
    dest: "{{ docker_config_location }}/adguard/AdGuardHome.yaml"
    owner: root
    group: root
    mode: 0644
  tags: config

- name: setup adguard docker container
  docker_container:
    name: adguard
    image: adguard/adguardhome:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.adguard }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.adguard }}"
    purge_networks: yes
    volumes:
      - "data_adguard:/opt/adguardhome/work"
      - "{{ docker_config_location }}/adguard:/opt/adguardhome/conf"
    restart: yes
    restart_policy: always
    state: started
    labels:
      traefik.http.routers.adguard.tls: "true"
      traefik.http.routers.adguard.tls.certresolver: "le"
      traefik.http.services.adguard.loadbalancer.server.port: "80"

