---
# container from: https://hub.docker.com/r/adguard/adguardhome

- name: Create a volume for adguard data
  community.docker.docker_volume:
    name: data_adguard

- name: Create adguard config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/adguard"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy config file
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "{{ docker.dir.config }}/adguard/AdGuardHome.yaml"
    owner: root
    group: root
    mode: "0644"
  tags: config

- name: Setup adguard docker container
  community.docker.docker_container:
    name: adguard
    image: adguard/adguardhome:latest
    networks:
      - name: services
        ipv4_address: "{{ docker.networks.services.ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks.services.hosts.adguard) \
          | ansible.utils.ipaddr('address') }}"
        ipv6_address: "{{ docker.networks.services.ipam[1].subnet | ansible.utils.ipaddr('network') }}\
          {{ docker.networks.services.hosts.adguard }}"
    volumes:
      - "data_adguard:/opt/adguardhome/work"
      - "{{ docker.dir.config }}/adguard:/opt/adguardhome/conf"
    restart: true
    restart_policy: always
    state: started
    labels:
      traefik.http.routers.adguard.rule: "Host(`{{ adguard_hostname }}`)"
      traefik.http.routers.adguard.tls: "true"
      traefik.http.routers.adguard.tls.certresolver: "le"
      traefik.http.services.adguard.loadbalancer.server.port: "80"
      traefik.http.routers.adguard.middlewares: "corsheaders@file"
