- name: Start iptvproxy docker container
  docker_container:
    name: iptv
    image: pierro777/iptv-proxy:v2.0.5
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.iptvproxy }}"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    env:
      M3U_URL: "{{ iptv_url }}"
      PORT: "8080"
      GIN_MODE: release
      HOSTNAME: "iptv.frai.se"
      HTTPS: "1"
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
      USER: "{{ iptvproxy_user }}"
      PASSWORD: "{{ iptvproxy_password }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.iptv.tls: "true"
      traefik.http.routers.iptv.tls.certresolver: "le"
      traefik.http.services.iptv.loadbalancer.server.port: "8080"
