---
# install Tautulli plex info
# https://github.com/Tautulli/Tautulli/wiki/Installation#docker

- name: Create a volume for tautulli config
  community.docker.docker_volume:
    name: config_tautulli

- name: Setup tautulli docker container
  community.docker.docker_container:
    name: tautulli
    image: ghcr.io/tautulli/tautulli:latest
    networks:
      - name: media
    volumes:
      - "config_tautulli:/config"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.tautulli.tls: "true"
      traefik.http.routers.tautulli.tls.certresolver: "le"
      traefik.http.services.tautulli.loadbalancer.server.port: "8181"
