# install calibre, book db
# https://registry.hub.docker.com/r/linuxserver/calibre
---
- name: Create a volume for calibre config
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - config_calibre
    - config_calibre-web

- name: Setup calibre docker container
  community.docker.docker_container:
    name: calibre
    image: linuxserver/calibre:latest
    networks:
      - name: macvlan333
    volumes:
      - "config_calibre:/config"
      - "/data/media:/media"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
      GUAC_USER: admin
      GUAC_PASS: "{{ guac_password }}"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.calibre.tls: "true"
      traefik.http.routers.calibre.tls.certresolver: "le"
      traefik.http.services.calibre.loadbalancer.server.port: "8080"
  tags: calibre-base,base

- name: Setup calibre_web docker container
  community.docker.docker_container:
    name: calibre-web
    image: linuxserver/calibre-web:latest
    networks:
      - name: macvlan333
    volumes:
      - "config_calibre-web:/config"
      - "/data/media/books:/books"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.books.rule: "Host(`books.frai.se`)"
      traefik.http.routers.books.tls: "true"
      traefik.http.routers.books.tls.certresolver: "le"
      traefik.http.services.books.loadbalancer.server.port: "8083"
  tags: calibre-web,web
