---
# install readarr book info
# https://hub.docker.com/r/linuxserver/readarr

- name: Create a volume for readarr config
  community.docker.docker_volume:
    name: config_readarr

- name: Setup readarr docker container
  community.docker.docker_container:
    name: readarr
    image: lscr.io/linuxserver/readarr:develop
    networks:
      - name: media
    volumes:
      - "config_readarr:/config"
      - "/data/media:/media"
      - "/downloads:/downloads"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.readarr.tls: "true"
      traefik.http.routers.readarr.tls.certresolver: "le"
      traefik.http.services.readarr.loadbalancer.server.port: "8787"
