- name: Debian based Setup
  block:
    - name: DEBIAN - install samba and nfs
      apt:
        name: ['samba' , 'nfs-kernel-server']
        state: latest
  when: ansible_os_family == "Debian"

- name: Arch based setup
  block:
    - name: ARCH - samba and nfs
      pacman:
        name: samba
        state: latest
        update_cache: yes
  when: ansible_os_family == "Archlinux"

- include_vars: "{{ ansible_os_family }}.yml"

- name: copy samba share config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify: restart samba service
