---
- name: Set overcommit_memory to 1 for valkey
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: true

- name: Start valkey docker container
  community.docker.docker_container:
    name: valkey
    image: valkey/valkey:alpine
    networks:
      - name: services
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
