---
- name: Set overcommit_memory to 1 for valkey
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: true

- name: Start valkey docker container
  community.docker.docker_container:
    name: valkey
    image: ghcr.io/valkey-io/valkey:alpine
    networks:
      - name: services
    dns_servers:
      - "{{ dns_servers.adguard.dco.ipv6 }}"
      - "{{ dns_servers.adguard.dco.ip }}"
      - "{{ dns_servers.adguard.home.ipv6 }}"
      - "{{ dns_servers.adguard.home.ip }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
