# install Radarr movie info
# https://hub.docker.com/r/linuxserver/radarr

- name: Create a volume for radarr config
  docker_volume:
    name: config_radarr

- name: setup radarr docker container
  docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.radarr }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.radarr }}"
    purge_networks: yes
    volumes:
      - "config_radarr:/config"
      - "/data/media:/data"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: yes
    pull: true
