---
# install Radarr movie info
# https://hub.docker.com/r/linuxserver/radarr

- name: Create a volume for radarr config
  community.docker.docker_volume:
    name: config_radarr

- name: Setup radarr docker container
  community.docker.docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    networks:
      - name: macvlan333
    volumes:
      - "config_radarr:/config"
      - "/data/media:/media"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.radarr.tls: "true"
      traefik.http.routers.radarr.tls.certresolver: "le"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
