# setup jellyfin with a docker container
# container from: https://hub.docker.com/r/jellyfin/jellyfin/

- name: create jellyfin config directory
  file:
    path: /data/jellyfin
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: setup jellyfin docker container
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.jellyfin}}"
    purge_networks: yes
    volumes:
      - "/data/jellyfin/config:/config"
      - "/data/jellyfin/cache:/cache"
      - "/data/plex/media:/media"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: "le"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
