# install lancache from: http://lancache.net/docs/containers/monolithic/

- name: create lancache directory
  file:
    path: "{{ docker_data_location }}/lancache/cache"
    state: directory
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    recurse: yes

- name: setup lancache docker container
  docker_container:
    name: lancache
    image: lancachenet/monolithic:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.lancache_monolitic }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.lancache_monolitic }}"
    env:
      CACHE_DISK_SIZE: "500000m"
      CACHE_MAX_AGE: "365d"
    purge_networks: yes
    volumes:
      - "{{ docker_data_location }}/lancache/cache:/data/cache"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
