# install lancache from: http://lancache.net/docs/containers/monolithic/
    
- name: setup lancache docker container
  docker_container:
    name: lancache
    image: lancachenet/monolithic:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.lancache_monolitic }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.lancache_monolitic }}"
    env:
      CACHE_DISK_SIZE: "500000m"
      CACHE_MAX_AGE: "365d"
    purge_networks: yes
    volumes:
      - "/lancache:/data/cache"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
