# setup zigbee2mqtt with a docker container
# container from: https://www.zigbee2mqtt.io/guide/installation/02_docker.html

- name: Create mqtt config directory
  ansible.builtin.file:
    path: "{{ docker_config_location }}/z2m"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy config file to docker volume
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ docker_config_location }}/z2m/configuration.yaml"
    mode: "0755"
    owner: root
    group: root

- name: Setup zigbee2mqtt docker container
  community.docker.docker_container:
    name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    networks:
      - name: macvlan333
    volumes:
      - "{{ docker_config_location }}/z2m:/app/data"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/ttyUSB0:/dev/ttyACM0"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.z2m.rule: "Host(`z2m.frai.se`)"
      traefik.http.routers.z2m.tls: "true"
      traefik.http.routers.z2m.tls.certresolver: "le"
      traefik.http.services.z2m.loadbalancer.server.port: "8080"
