---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "frai.se"
subtitle: "Welcome"
logo: "https://i.imgur.com/UgSg9YM.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

connectivityCheck: true

# Optionnal theme customization
theme: default
colors:
  light:
    highlight-secondary: "#009688"
    highlight-primary: "#00796B"
    highlight-hover: "#B2DFDB"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "👋 Demo !"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Tweakers"
    icon: "fas fa-newspaper"
    url: "https://tweakers.net"
  - name: "Reddit"
    icon: "fab fa-reddit-alien"
    url: "https://reddit.com/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: "fas fa-layer-group"
    items:
      - name: "Syncthing"
        logo: "https://upload.wikimedia.org/wikipedia/commons/8/83/SyncthingAugustLogo.png"
        url: "https://syncthing.frai.se"
        subtitle: "Config syncing"
      - name: "Home Assistant"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/1200px-Home_Assistant_Logo.svg.png"
        url: "https://ha.frai.se"
        subtitle: "Home automation platform"
  - name: "Gaming"
    icon: "fas fa-gamepad"
    items:
      - name: "ACServer"
        logo: "https://i.imgur.com/cf7S3Xe.png"
        url: "https://acserver.frai.se"
        subtitle: "AC Server Frontend"
      - name: "ACCServer"
        logo: "https://i.imgur.com/cf7S3Xe.png"
        url: "https://accserver.frai.se"
        subtitle: "ACC Server Frontend"
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Plex"
        logo: "https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png"
        url: "https://plex.frai.se"
        subtitle: "Self-hosted media player"
      - name: "Jackett"
        logo: "https://developer.asustor.com/uploadIcons/0020_23588_1445715271_icon.png"
        url: "https://jackett.frai.se"
        subtitle: "Torrent api proxy"
      - name: "Deluge"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Deluge-Logo.svg/600px-Deluge-Logo.svg.png"
        url: "https://deluge.frai.se"
        subtitle: "Torrent client"
  - name: "Networking"
    icon: "fas fa-ethernet"
    items:
      - name: "Pi-Hole"
        logo: "https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png"
        url: "https://pihole.frai.se"
        subtitle: "Network wide ad-blocker"
      - name: "Mikrotik"
        logo: "https://pbs.twimg.com/profile_images/479585638560182272/Qa8mmn1I.png"
        url: "https://ironman.frai.se:8443"
        subtitle: "Web management router"
      - name: "Portainer"
        logo: "https://avatars1.githubusercontent.com/u/22225832"
        url: "https://portainer.frai.se"
        subtitle: "Container orchestrator"
      - name: "Traefik"
        logo: "https://blog.carroarmato0.be/content/images/2019/02/traefik.logo.bright@3x.svg"
        url: "http://10.33.0.10:8080/"
        subtitle: "Reverse proxy"
        tag: local
      - name: "UNMS"
        logo: "https://i.imgur.com/17hyHHu.png"
        url: "https://unms.frai.se"
        subtitle: "Ubiquiti network management"
  - name: "Monitoring"
    icon: "fab fa-cloudscale"
    items:
      - name: "Grafana"
        logo: "https://grafana.com/static/img/logos/grafana_logo_swirl-events.svg"
        subtitle: "Dashboarding instance"
        url: "https://grafana.frai.se"
      - name: "Prometheus"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1200px-Prometheus_software_logo.svg.png"
        subtitle: "Monitoring metrics database"
        tag: "local"
        url: "http://10.33.0.23:9090/"
