- name: install mergerfs packages
  apt:
    name: ['mergerfs', 'parted', 'xfsprogs']
    state: latest
  when: ansible_os_family == "Debian"

- name: make storage mountpoints
  file:
    state: directory
    path: /mnt/disk{{ item }}
    owner: nobody
    group: nogroup
    mode: 0777
  with_sequence: start=1 end=2

- name: make parity mountpoints
  file:
    state: directory
    path: /mnt/parity{{ item }}
    owner: nobody
    group: nogroup
    mode: 0777
  with_sequence: start=1 end=1

- name: make data mountpoint
  file:
    state: directory
    path: /data
    owner: nobody
    group: nogroup
    mode: 0777

- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/{{ item }}
  register: item_info
  loop:
    - sda
    - sdc

- name: Partition harddrives if needed
  community.general.parted:
    device: /dev/{{ item }}
    number: 1
    state: present
  when: item_info.results[item_index].partitions|length<=0
  loop:
    - sda
    - sdc
  loop_control:
    index_var: item_index

- name: initiate filesystem on partitions if needed
  filesystem:
     fstype: xfs
     dev: /dev/{{ item }}
     force: yes
  when: item_info.results[item_index].partitions|length<=0
  loop:
    - sda1
    - sdc1
  loop_control:
    index_var: item_index

- name: mount disks
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    state: mounted
  with_items:
    - { name: /mnt/parity1, src: /dev/disk/by-id/ata-ST2000DM001-1CH164_S1E2JA4E-part1, fs: xfs}
    - { name: /mnt/disk1, src: /dev/disk/by-id/ata-WDC_WD10EADS-11M2B2_WD-WCAV59971942-part1, fs: xfs}

- name: mount mergerfs array
  mount:
    name: /data
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    state: mounted

- name: set nobody permissions
  file:
    state: directory
    path: /data
    owner: nobody
    group: nogroup
    mode: 0777
