---
- name: Create a volume for prowlarr config
  community.docker.docker_volume:
    name: config_prowlarr

- name: Setup flaresolverr docker container
  community.docker.docker_container:
    name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    networks:
      - name: media
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: Setup prowlarr docker container
  community.docker.docker_container:
    name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - name: media
    volumes:
      - "config_prowlarr:/config"
      - "data_torrent_watch:/downloads"
    env:
      TZ: "Europe/Brussels"
      PUID: "65534"
      PGID: "65534"
      UMASK: "002"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.routers.prowlarr.tls.certresolver: "le"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
