---
- name: Create loki config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/loki"
    state: directory
    mode: "0755"
    owner: "10001"
    group: "10001"

- name: Loki data volume
  community.docker.docker_volume:
    name: data_loki

- name: Copy configuration templates to directory
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ docker.dir.config }}/loki/{{ item }}"
    owner: "10001"
    group: "10001"
    mode: "0644"
  loop:
    - loki-config.yaml

- name: Setup loki docker container
  community.docker.docker_container:
    name: loki
    image: grafana/loki:latest
    networks:
      - name: monitoring
        ipv4_address: "{{ docker.networks.monitoring.ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks.monitoring.hosts.loki) \
          | ansible.utils.ipaddr('address') }}"
        ipv6_address: "{{ docker.networks.monitoring.ipam[1].subnet | ansible.utils.ipaddr('network') }}\
          {{ docker.networks.monitoring.hosts.loki }}"
    dns_servers:
      - "{{ dns_servers.adguard.dco.ipv6 }}"
      - "{{ dns_servers.adguard.dco.ip }}"
      - "{{ dns_servers.adguard.home.ipv6 }}"
      - "{{ dns_servers.adguard.home.ip }}"
    volumes:
      - "{{ docker.dir.config }}/loki:/mnt/config"
      - "data_loki:/loki"
    command:
      - "-config.file=/mnt/config/loki-config.yaml"
      - "-common.storage.filesystem.chunk-directory=/loki/chunks"
      - "-common.path-prefix=/loki"
      - "-log.level=warn"
      - "-auth.enabled=false"
      - "-common.storage.ring.store=inmemory"
      - "-frontend.encoding=protobuf"
      - "-ruler.alertmanager-url=http://prometheus-alertmanager:9093"
      - "-ruler.storage.local.directory=/loki/rules"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.loki.tls: "true"
      traefik.http.routers.loki.tls.certresolver: "le"
      traefik.http.services.loki.loadbalancer.server.port: "3100"
