---
# setup grocy with a docker container
# container from: https://github.com/bastienwirtz/homer

- name: Create homer config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/homer"
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Copy config file
  ansible.builtin.copy:
    src: config.yml
    dest: "{{ docker.dir.config }}/homer/config.yml"
    mode: "0644"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
  tags: config

- name: Setup homer docker container
  community.docker.docker_container:
    name: homer
    image: b4bz/homer:latest
    networks:
      - name: services
    volumes:
      - "{{ docker.dir.config }}/homer/config.yml:/www/assets/config.yml:ro"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
