---
# setup grocy with a docker container
# container from: https://github.com/bastienwirtz/homer

- name: Create homer config directory
  ansible.builtin.file:
    path: "{{ docker_config_location }}/homer"
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Copy config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ docker_config_location }}/homer/config.yml"
    mode: "0644"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
  tags: config

- name: Setup homer docker container
  community.docker.docker_container:
    name: homer
    image: b4bz/homer:latest
    networks:
      - name: macvlan333
    volumes:
      - "{{ docker_config_location }}/homer:/www/assets"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
