# setup grocy with a docker container
# container from: https://github.com/bastienwirtz/homer

- name: create homer config directory
  file:
    path: "{{ docker_data_location }}/homer"
    state: directory
    mode: 0755
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: copy config file
  copy:
    src: config.yml
    dest: "{{ docker_data_location }}/homer/config.yml"
    mode: 0644
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
  tags: config

- name: setup homer docker container
  docker_container:
    name: homer
    image: b4bz/homer:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.homer }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.homer }}"
    purge_networks: yes
    volumes:
      - "{{ docker_data_location }}/homer:/www/assets"
    env:
      UID: "{{ nobody.user }}"
      GID: "{{ nobody.group }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
