---
# install Sonarr series info
# https://docs.linuxserver.io/images/docker-sonarr/

- name: Create a volume for sonarr config
  community.docker.docker_volume:
    name: config_sonarr

- name: Setup sonarr docker container
  community.docker.docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    networks:
      - name: media
    volumes:
      - "config_sonarr:/config"
      - "/data/media:/media"
      - /downloads:/downloads
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      TZ: "Etc/UTC"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.tls.certresolver: "le"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
