# setup nextcloud with a docker container
# container from: https://github.com/nextcloud/docker

- name: create nextcloud config directory
  file:
    path: /data/nextcloud/
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes


- name: setup nextcloud docker container
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    networks:
      - name: fraise_network
        ipv4_address: "{{ docker_network.nextcloud }}"
    purge_networks: yes
    volumes:
      - "/data/nextcloud:/var/www/html"
      - "/data:/data"
    restart: yes
    restart_policy: always
    state: started
    pull: true
