# setup invoiceninja with a docker container
# container from: https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose.yml

- name: create invoiceninja config directory
  file:
    path: /data/invoiceninja/{{ item.item }}
    state: directory
    mode: 0755
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - { item: mysql, user: mysql, group: data}
    - { item: caddy, user: gianni, group: data}

- name: setup mariadb docker container
  docker_container:
    name: mariadb_invoice
    image: mariadb:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.mariadb_invoice }}"
    volumes:
      - "/data/invoiceninja/mysql:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: ninja
      MYSQL_USER: ninja
      MYSQL_PASSWORD: ninja
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: Create a docker volume
  community.general.docker_volume:
    name: "{{ item }}"
  with_items:
    - invoice_content
    - invoice_data

- name: setup invoiceninja docker container
  docker_container:
    name: invoiceninja
    image: invoiceninja/invoiceninja:5
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.invoiceninja }}"
    env:
      APP_URL: "{{ invoiceninja_app_url }}"
      APP_KEY: "{{ invoiceninja_key }}"
      MULTI_DB_ENABLED: "false"
      DB_HOST1: "{{ docker_network.mariadb_invoice }}"
    volumes:
      - "invoice_content:/var/www/app/public"
      - "invoice_data:/var/www/app/storage"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: copy caddy file
  template:
    src: Caddyfile.j2
    dest: /data/invoiceninja/caddy/Caddyfile
    mode: 0644
    owner: gianni
    group: data

- name: setup caddy invoiceninja
  docker_container:
    name: caddy_invoiceninja
    image: caddy:alpine
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.caddy }}"
    env:
      APP_URL: "{{ invoiceninja_app_url }}"
    volumes:
      - "/data/invoiceninja/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "invoice_content:/var/www/app/public"
      - "invoice_data:/var/www/app/storage"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.invoiceninja.rule: "Host(`invoiceninja.unitix.be`)"
      traefik.http.routers.invoiceninja.tls: "true"
      traefik.http.routers.invoiceninja.tls.certresolver: "le"
      traefik.http.services.invoiceninja.loadbalancer.server.port: "80"
