# setup jackett with a docker container
# container from: https://hub.docker.com/r/linuxserver/jackett/
---
- name: Create a volume for jackett config
  community.docker.docker_volume:
    name: config_jackett

- name: Setup jackett docker container
  community.docker.docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    networks:
      - name: macvlan333
        # ipv4_address: "{{ docker.network.ipv4_prefix }}{{ docker.network.hosts.jackett }}"
        # ipv6_address: "{{ docker.network.ipv6_prefix }}{{ docker.network.hosts.jackett }}"
    volumes:
      - "config_jackett:/config"
      - "data_deluge_watch:/downloads"
    env:
      TZ: "Europe/Brussels"
      PUID: "65534"
      PGID: "65534"
      PASSWORD: "{{ jackett_pass }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.jackett.tls: "true"
      traefik.http.routers.jackett.tls.certresolver: "le"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"

- name: S flaresolverr docker container
  community.docker.docker_container:
    name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    networks:
      - name: macvlan333
        # ipv4_address: "{{ docker.network.ipv4_prefix }}{{ docker.network.hosts.flaresolverr }}"
        # ipv6_address: "{{ docker.network.ipv6_prefix }}{{ docker.network.hosts.flaresolverr }}"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
