# setup jackett with a docker container
# container from: https://hub.docker.com/r/linuxserver/jackett/

- name: Create a volume for jackett config
  docker_volume:
    name: config_jackett

- name: setup jackett docker container
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.jackett }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.jackett }}"
    purge_networks: yes
    volumes:
      - "config_jackett:/config"
      - "{{ docker_data_location }}/deluge/watch:/downloads"
    env:
      TZ: "Europe/Brussels"
      PUID: "65534"
      PGID: "65534"
      PASSWORD: "{{ jackett_pass }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.jackett.tls: "true"
      traefik.http.routers.jackett.tls.certresolver: "le"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"

- name: setup flaresolverr docker container
  docker_container:
    name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.flaresolverr }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.flaresolverr }}"
    purge_networks: yes
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

