# setup mosquitto with a docker container
# container from: https://hub.docker.com/_/eclipse-mosquitto
---
- name: Create mqtt config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/mqtt"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy config file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: "{{ docker.dir.config }}/mqtt/mosquitto.conf"
    owner: root
    group: root
    mode: "0755"

- name: Create a volume for persistent data
  community.docker.docker_volume:
    name: "data_mqtt"

- name: Setup mosquitto mqtt docker container
  community.docker.docker_container:
    name: mosquitto
    image: eclipse-mosquitto:latest
    networks:
      - name: services
    volumes:
      - "data_mqtt:/mosquitto/data"
      - "{{ docker.dir.config }}/mqtt:/mosquitto/config"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
