auths:
  fraise_v2:
    community: frai.se
    version: 2

modules:
  if_mib:
    walk:
      - sysDescr
      - sysUpTime
      - ifDescr  # interfaces
      - ifAdminStatus  # interfaces
      - ifOperStatus  # interfaces
      - ifLastChange  # interfaces
      - ifHCInOctets  # ifXTable
      - ifHCOutOctets  # ifXTable
      - ifName  # ifXTable
      - ifAlias  # ifXTable
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifDescr

# Mikrotik
  mikrotik:
    walk:
      - hrProcessorLoad
      - hrStorageSize
      - hrStorageUsed
      - mtxrFirmwareVersion
      - mtxrLicVersion
      - mtxrHealth
