---
- name: Create a volume for sabnzbd config
  community.docker.docker_volume:
    name: config_sabnzbd

- name: Setup sabnzbd docker container
  community.docker.docker_container:
    name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    networks:
      - name: media
    volumes:
      - "config_sabnzbd:/config"
      - "/downloads:/downloads"
      - "/data/media:/media"
    env:
      TZ: "Europe/Brussels"
      PUID: "65534"
      PGID: "65534"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.routers.sabnzbd.tls.certresolver: "le"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
