---
# - name: Create graphite config directory
#   ansible.builtin.file:
#     path: "{{ docker.dir.config }}/prometheus_graphite"
#     state: directory
#     mode: "0755"
#     owner: "{{ nobody.group }}"
#     group: "{{ nobody.group }}"

# - name: Copy graphite config
#   ansible.builtin.copy:
#     src: graphite-mapping.conf
#     dest: "{{ docker.dir.config }}/prometheus_graphite/mapping.conf"
#     owner: "{{ nobody.user }}"
#     group: "{{ nobody.group }}"
#     mode: "0755"

# port = 9108, 9109(graphite)
- name: Setup prometheus graphite exporter
  community.docker.docker_container:
    name: prometheus-graphite_exporter
    image: prom/graphite-exporter:latest
    networks:
      - name: macvlan333
    # volumes:
    #   - "{{ docker.dir.config }}/prometheus_graphite/graphite_mapping.conf:/tmp/graphite_mapping.conf:ro"
    # command: "--graphite.mapping-config=/tmp/graphite_mapping.conf"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
