# setup prometheus with a docker container
# container from: https://prometheus.io/docs/prometheus/latest/installation/
---

- name: Setup blackbox exporter
  ansible.builtin.import_tasks: blackbox_exporter.yml
  tags: blackbox, blackbox_exporter, blackbox-exporter
  when: prometheus.features.blackbox | default (true)

- name: Setup snmp exporter
  ansible.builtin.import_tasks: snmp_exporter.yml
  tags: snmp, snmp_exporter, snmp-exporter
  when: prometheus.features.snmp | default (false)

- name: Setup speedtest exporter
  ansible.builtin.import_tasks: speedtest_exporter.yml
  tags: speedtest, speedtest_exporter, speedtest-exporter
  when: prometheus.features.speedtest | default (false)

- name: Setup ipmi exporter
  ansible.builtin.import_tasks: ipmi_exporter.yml
  tags: ipmi, ipmi_exporter, ipmi-exporter
  when: prometheus.features.ipmi | default (false)

- name: Setup alertmanager
  ansible.builtin.import_tasks: alertmanager.yml
  tags: alertmanager, alerts, alert
  when: prometheus.features.alertmanager | default (false)

- name: Setup prometheus
  ansible.builtin.import_tasks: base.yml
  tags: prometheus,base
