- name: create snmp config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ nobody.group }}"
    group: "{{ nobody.group }}"
    recurse: yes
  with_items:
    - "{{ docker_config_location }}/prometheus_snmp"

- name: copy generator config
  copy:
    src: generator.yml
    dest: "{{ docker_config_location }}/prometheus_snmp/generator.yml"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0755

- name: copy mibs
  copy:
    src: mibs/
    dest: "{{ docker_config_location }}/prometheus_snmp/mibs/"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: 0755

- name: setup prometheus snmp generator
  docker_container:
    name: prometheus-snmp-generator
    image: prom/snmp-generator:latest
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/prometheus_snmp:/opt"
    restart: yes
    restart_policy: no
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: wait for generator to have created snmp.yml
  pause:
    seconds: 10

- name: setup prometheus snmp exporter
  docker_container:
    name: prometheus-snmp
    image: prom/snmp-exporter:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.prometheus_snmp_exporter }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.prometheus_snmp_exporter }}"
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/prometheus_snmp/snmp.yml:/snmp.yml:ro"
    command: "--config.file=/snmp.yml"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: remove generator container
  docker_container:
    name: prometheus-snmp-generator
    state: absent   
