- name: Create snmp config directory
  ansible.builtin.file:
    path: "{{ docker_config_location }}/prometheus_snmp"
    state: directory
    mode: "0755"
    owner: "{{ nobody.group }}"
    group: "{{ nobody.group }}"

- name: Copy generator config
  ansible.builtin.copy:
    src: generator.yml
    dest: "{{ docker_config_location }}/prometheus_snmp/generator.yml"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: "0755"

- name: Copy mibs
  ansible.builtin.copy:
    src: mibs/
    dest: "{{ docker_config_location }}/prometheus_snmp/mibs/"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"
    mode: "0755"

- name: Setup prometheus snmp generator
  community.docker.docker_container:
    name: prometheus-snmp-generator
    image: prom/snmp-generator:latest
    volumes:
      - "{{ docker_config_location }}/prometheus_snmp:/opt"
    restart: true
    restart_policy: false
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: Wait for generator to have created snmp.yml
  ansible.builtin.pause:
    seconds: 10

- name: Setup prometheus snmp exporter
  community.docker.docker_container:
    name: prometheus-snmp
    image: prom/snmp-exporter:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.prometheus_snmp_exporter }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.prometheus_snmp_exporter }}"
    volumes:
      - "{{ docker_config_location }}/prometheus_snmp/snmp.yml:/snmp.yml:ro"
    command: "--config.file=/snmp.yml"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"

- name: Remove generator container
  community.docker.docker_container:
    name: prometheus-snmp-generator
    state: absent
