---
- name: Create a volume for postiz
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - config_postiz
    - data_postiz

- name: Get postgres container ip
  community.docker.docker_container_info:
    name: postgres
  register: result_containerip

- name: Create a new database with name "postiz"
  community.general.postgresql_db:
    name: postiz
    login_host: "{{ result_containerip.container.NetworkSettings.Networks.services.IPAddress }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
  delegate_to: localhost
  become: false

- name: Setup postiz docker container
  community.docker.docker_container:
    name: postiz
    image: ghcr.io/gitroomhq/postiz-app:latest
    networks:
      - name: services
    env:
      MAIN_URL: "https://postiz.unitix.gg"
      FRONTEND_URL: "https://postiz.unitix.gg"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.unitix.gg/api"
      JWT_SECRET: "{{ postiz_jwt_token }}"
      DATABASE_URL: 'postgres://{{ postgres_user }}:{{ postgres_password | regex_replace("#", "%23") }}@postgres/postiz?sslmode=disable'
      REDIS_URL: "redis://valkey"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
      REDDIT_CLIENT_ID: "{{ postiz_reddit_client_id }}"
      REDDIT_SECRET: "{{ postiz_reddit_secret }}"
      DISCORD_CLIENT_ID: "{{ postiz_discord_client_id }}"
      DISCORD_SECRET: "{{ postiz_discord_secret }}"
    volumes:
      - config_postiz:/config/
      - data_postiz:/uploads/
    state: started
    restart: true
    restart_policy: always
    pull: true
    labels:
      traefik.http.routers.postiz.tls: "true"
      traefik.http.routers.postiz.rule: "Host(`postiz.unitix.gg`)"
      traefik.http.routers.postiz.tls.certresolver: "le"
      traefik.http.services.postiz.loadbalancer.server.port: "5000"
