- name: SETUP - install sudo package
  ansible.builtin.apt:
    name:
      - sudo
    state: present
  vars:
    ansible_become_method: su

- name: SETUP - Allow wheel user group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
  vars:
    ansible_become_method: su

- name: SETUP - temporarily add debian to the sudo group
  ansible.builtin.user:
    name: debian
    groups: sudo
    append: true
  vars:
    ansible_become_method: su

- name: SETUP - reset connection so sudo permission is recognized
  ansible.builtin.meta: reset_connection

- name: SETUP - Generate random password
  ansible.builtin.set_fact:
    new_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,.,_,! length=15') }}"

- name: SETUP - Add password to file
  ansible.builtin.lineinfile:
    path: "{{ local_password_location }}"
    line: "{{ lookup('pipe', 'date -u +%FT%TZ') }};{{ inventory_hostname }};{{ new_password }}"
    create: true
    mode: "0755"
  delegate_to: localhost
  become: false

- name: SETUP - Change user password for root
  ansible.builtin.user:
    name: "root"
    password: "{{ new_password | password_hash('sha512', 'mysecretsalt') }}"
