- name: SETUP - install sudo package
  apt:
    name:
      - sudo
    state: latest
  vars:
    ansible_become_method: su

- name: SETUP - Allow wheel user group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
  vars:
    ansible_become_method: su

- name: SETUP - temporarily add debian to the sudo group
  user:
    name: debian
    groups: wheel
    append: yes
  vars:
    ansible_become_method: su

- name: SETUP - reset connection so sudo permission is recognized
  meta: reset_connection

- name: SETUP - Generate random password
  set_fact:
    new_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,.,_,! length=15' ) }}"

- name: SETUP - Add password to file
  lineinfile:
    path: "{{ local_password_location }}"
    line: "{{ lookup('pipe', 'date -u +%FT%TZ')}};{{ inventory_hostname }};{{new_password}}"
    create: yes
  delegate_to: localhost
  become: false

- name: SETUP - Change user password for root
  user:
    name: "root"
    password: "{{ new_password | password_hash('sha512', 'mysecretsalt') }}"
