- name: HOSTNAME - Update hostname
  hostname:
    name: "{{ inventory_hostname | replace('_', '-') }}"

- name: HOSTNAME - Set in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1	{{ inventory_hostname | replace('_', '-') }}.frai.se {{ inventory_hostname | replace('_', '-') }}"