---
- name: HOSTNAME - Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | replace('_', '-') }}"

- name: HOSTNAME - Set in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1	{{ inventory_hostname | replace('_', '-') }}.{{ dns.domain }} {{ inventory_hostname | replace('_', '-') }}"
