- name: SSHD - Change ssh configs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^(# *)?PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^(# *)?UsePAM '
      line: 'UsePAM yes'
    - regexp: '^(# *)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
    - regexp: '^(# *)?PermitEmptyPasswords '
      line: 'PermitEmptyPasswords no'
    - regexp: '^(# *)?ChallengeResponseAuthentication '
      line: 'ChallengeResponseAuthentication no'
    - regexp: '^(# *)?Port '
      line: 'Port 1830'
  notify: Restart sshd

- name: USER - Flush handlers
  ansible.builtin.meta: flush_handlers
