---
- name: Run debian tasks
  when: ansible_os_family == "Debian"
  block:
    - name: PACKAGES - Update apt cache so packages are available to download
      ansible.builtin.apt:
        update_cache: true

    - name: PACKAGES - Install default packages
      ansible.builtin.apt:
        name:
          - curl
          - fail2ban
          - gdu
          - git
          - htop
          - ifupdown2
          - net-tools
          - nfs-common
          - nmap
          - mtr
          - parted
          - python3-pip
          - qemu-guest-agent
          - traceroute
          - tcpdump
          - vim

    - name: PACKAGES - Enable qemu guest agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started
        enabled: true
      when: vm | default(true)

    - name: PACKAGES - uninstall cloud-init
      ansible.builtin.apt:
        state: absent
        name:
          - cloud-init
          - netplan.io
        purge: true
