---
- name: run debian tasks
  block:
    - name: PACKAGES - Update all to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
      tags: upgrade

    - name: PACKAGES - Install default packages
      ansible.builtin.apt:
        name:
          - curl
          - fail2ban
          - git
          - htop
          - ncdu
          - net-tools
          - nmap
          - ntp
          - mtr
          - parted
          - python3-pip
          - traceroute
          - tcpdump
          - vim
  when: ansible_os_family == "Debian"
