- name: run debian tasks
  block: 
    - name: PACKAGES - Update all to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
      tags: upgrade

    - name: PACKAGES - Install default packages
      apt:
        name: 
          - curl
          - fail2ban
          - git
          - htop
          - ncdu
          - net-tools
          - nmap
          - ntp   
          - mtr
          - python3-pip
          - traceroute
          - tcpdump
          - vim
  when: ansible_os_family == "Debian"          
