---
- name: Run debian tasks
  when: ansible_os_family == "Debian"
  block:
    - name: PACKAGES - Update apt cache so packages are available to download
      ansible.builtin.apt:
        update_cache: true

    - name: PACKAGES - Install default packages
      ansible.builtin.apt:
        name:
          - curl
          - fail2ban
          - git
          - htop
          - gdu
          - net-tools
          - nmap
          - mtr
          - parted
          - python3-pip
          - traceroute
          - tcpdump
          - vim
