---
- name: MOUNTS - Make mountpoints
  ansible.builtin.file:
    state: directory
    path: "{{ item.mountpoint }}"
    # owner: nobody
    # group: nogroup
    mode: "0775"
  loop: "{{ mounts }}"

- name: MOUNTS - Read device information (always use unit when probing)
  community.general.parted:
    device: "{{ item.source }}"
  register: item_info
  loop: "{{ mounts }}"
  when: item.fs != 'nfs'

- name: MOUNTS - Partition harddrives if needed
  community.general.parted:
    device: "{{ item.source }}"
    number: 1
    state: present
    label: gpt
  when:
    - item.fs != 'nfs'
    - item_info.results[item_index].partitions|length<=0
  loop: "{{ mounts }}"
  loop_control:
    index_var: item_index

- name: MOUNTS - Initiate filesystem on partitions if needed
  community.general.filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ item.source }}-part1"
    force: true
  when:
    - item.fs != 'nfs'
    - item_info.results[item_index].partitions|length<=0
  loop: "{{ mounts }}"
  loop_control:
    index_var: item_index

- name: MOUNTS - Mount partitions to directories
  ansible.posix.mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.source if item.fs == 'nfs' else (item.source + '-part1') }}"
    fstype: "{{ item.fs }}"
    state: mounted
  loop: "{{ mounts }}"
