---
- name: MOUNTS - Make mountpoints
  ansible.builtin.file:
    state: directory
    path: /{{ item.dir }}
    owner: nobody
    group: nogroup
    mode: "0775"
  loop: "{{ mounts }}"

- name: MOUNTS - Read device information (always use unit when probing)
  community.general.parted:
    device: /dev/disk/by-id/{{ item.disk }}
  register: item_info
  loop: "{{ mounts }}"

- name: MOUNTS - Partition harddrives if needed
  community.general.parted:
    device: /dev/disk/by-id/{{ item.disk }}
    number: 1
    state: present
  when: item_info.results[item_index].partitions|length<=0
  loop: "{{ mounts }}"
  loop_control:
    index_var: item_index

- name: MOUNTS - Initiate filesystem on partitions if needed
  community.general.filesystem:
    fstype: "{{ item.fs }}"
    dev: /dev/disk/by-id/{{ item.disk }}-part1
    force: true
  when: item_info.results[item_index].partitions|length<=0
  loop: "{{ mounts }}"
  loop_control:
    index_var: item_index

- name: MOUNTS - Mount partitions to directories
  ansible.posix.mount:
    name: /{{ item.dir }}
    src: /dev/disk/by-id/{{ item.disk }}-part1
    fstype: ext4
    state: mounted
  loop: "{{ mounts }}"
