- name: Debian Setup
  block:
    - name: update apt packages
      apt:
        upgrade: dist
        update_cache: yes
    - name: install default packages
      apt:
        name: ['ntp', 'vim', 'sudo', 'curl', 'git', 'htop', 'net-tools', 'fail2ban', 'python-pip', 'traceroute', 'tcpdump', 'ncdu']
        state: latest
    - import_tasks: node_exporter.yaml
  when: ansible_os_family == "Debian"

- name: Arch Setup
  block:
    - name: update & upgrade packages
      pacman:
        update_cache: yes
        upgrade: yes
    - name: install default packages
      pacman:
        name: ['ntp', 'vim', 'sudo', 'curl', 'git', 'htop', 'net-tools', 'fail2ban', 'python-pip', 'traceroute', 'tcpdump', 'ncdu', 'prometheus-node-exporter']
        state: latest
  when: ansible_os_family == "Archlinux"

- name: set timezone to UTC
  timezone:
    name: Etc/UTC

- name: create default_user user if not exists
  user:
    name: "{{ default_user }}"
    groups: sudo
    append: yes
    shell: /bin/bash

- name: Allow default_user user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ default_user }}'
    line: '{{ default_user }} ALL=(ALL) NOPASSWD:ALL'

- name: create data group if not exists
  group:
    name: data
    state: present

- name: add users to data group
  user:
    name: "{{ item }}"
    groups: data
    append: yes
  with_items:
    - root
    - "{{ default_user }}"
    - http

- import_tasks: ssh.yaml
