---
interfaces:
  - name: enp38s0
    description: LACP1
    mode: manual
  - name: enp39s0
    description: LACP2
    mode: manual
  - name: enx32a4e1ec57f1
    description: UNUSED
    mode: manual
  - name: bond0
    description: LACP
    mode: manual
    mtu: 9216
    bond:
      mode: 802.3ad
      slaves:
        - enp38s0
        - enp39s0
  - name: vmbr0
    description: Main Bridge
    mode: manual
    mtu: 9216
    bridge:
      ports: bond0
      stp: "off"
      vlan:
        vids: 2-4094
  - name: vlan33
    description: MGMT Vlan
    mode: dhcp
    vlan:
      device: vmbr0
      id: 33

