# setup traefik with a docker container
# container from: https://docs.traefik.io/getting-started/quick-start/

- name: create traefik config directory
  file:
    path: /data/traefik/letsencrypt
    state: directory
    mode: 0600
    owner: root
    group: root
    recurse: yes

- name: copy Traefik config
  template:
    src: "{{ item }}.j2"
    dest: /data/traefik/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - traefik.yml
    - custom_rules.yml

- name: setup traefik docker container
  docker_container:
    name: traefik
    image: traefik:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.traefik }}"
    purge_networks: yes
    volumes:
      - "/data/traefik/letsencrypt:/letsencrypt"
      - "/data/traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/data/traefik/custom_rules.yml:/etc/traefik/custom_rules.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
