---
# setup traefik with a docker container
# container from: https://docs.traefik.io/getting-started/quick-start/
- name: Create traefik user to minimize privileges
  ansible.builtin.user:
    name: "traefik"
    comment: "traefik user"
    system: true

- name: Create traefik config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/{{ item }}"
    state: directory
    mode: "0700"
    owner: traefik
    group: traefik
  loop:
    - traefik
    - traefik/letsencrypt
    - traefik/secrets

- name: Copy Traefik config
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ docker.dir.config }}/traefik/{{ item }}"
    owner: traefik
    group: traefik
    mode: "0600"
  loop:
    - traefik.yml
    - custom_rules.yml

- name: Write Cloudflare Token to secret file
  ansible.builtin.copy:
    content: "{{ cloudflare_api_token }}"
    dest: "{{ docker.dir.config }}/traefik/secrets/cf_api_token"
    owner: traefik
    group: traefik
    mode: "0400"

- name: Create a volume for letsencrypt
  community.docker.docker_volume:
    name: data_traefik_letsencrypt

- name: Set network var
  ansible.builtin.set_fact:
    traefik_network: "{{ traefik_network | default('services') }}"

- name: Gather numeric UID and GID of the host traefik user
  ansible.builtin.getent:
    database: passwd
    key: traefik

- name: Gather numeric GID of the host docker group
  ansible.builtin.getent:
    database: group
    key: docker

- name: Create dockerproxy docker network
  community.docker.docker_network:
    name: dockerproxy_network
    driver: bridge
    internal: true

- name: Setup dockerproxy docker container
  community.docker.docker_container:
    name: dockerproxy
    image: ghcr.io/wollomatic/socket-proxy:1
    networks:
      - name: dockerproxy_network
    dns_servers: "{{ dns.servers }}"
    command:
      - '-loglevel=info' # set to debug for far more logging
      - '-allowfrom=traefik'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - '-allowHEAD=/_ping'
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
    restart: true
    restart_policy: always
    state: started
    pull: true
    read_only: true
    cap_drop:
      - ALL
    security_opts:
      - no-new-privileges:true
    user: 65534:{{ getent_group['docker'][1] }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "false"
      wud.watch.digest: "true"

- name: Setup traefik docker container
  community.docker.docker_container:
    name: traefik
    image: traefik:latest
    user: "{{ getent_passwd['traefik'][1] }}:{{ getent_passwd['traefik'][2] }}"
    networks:
      - name: "{{ traefik_network }}"
        ipv4_address: "{{ docker.networks[traefik_network].ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks[traefik_network].hosts.traefik) \
          | ansible.utils.ipaddr('address') if docker.networks[traefik_network].hosts.traefik is defined else omit }}"
        ipv6_address: "{{ (docker.networks[traefik_network].ipam[1].subnet | ansible.utils.ipaddr('network') \
          + docker.networks[traefik_network].hosts.traefik | string) if docker.ipv6 | default(true)
          and docker.networks[traefik_network].hosts.traefik is defined else omit }}"
      - name: dockerproxy_network
    dns_servers: "{{ dns.servers }}"
    volumes:
      - "{{ docker.dir.config }}/traefik/letsencrypt:/letsencrypt"
      - "{{ docker.dir.config }}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "{{ docker.dir.config }}/traefik/custom_rules.yml:/etc/traefik/custom_rules.yml:ro"
      - "{{ docker.dir.config }}/traefik/secrets/cf_api_token:/run/secrets/cf_api_token:ro"
    mounts:
      - target: /tmp
        type: tmpfs
    env:
      CF_API_EMAIL: "{{ cloudflare_api_email }}"
      CF_API_KEY_FILE: "/run/secrets/cf_api_token"
    read_only: true
    capabilities:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    security_opts:
      - no-new-privileges:true
    restart: true
    restart_policy: always
    state: healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    pull: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: Host(`traefik.frai.se`)
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.certresolver: "le"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.services.api.loadbalancer.server.port: "8080"
