# setup traefik with a docker container
# container from: https://docs.traefik.io/getting-started/quick-start/

- name: create traefik config directory
  file:
    path: "{{ docker_config_location }}/traefik"
    state: directory
    mode: 0600
    owner: root
    group: root

- name: copy Traefik config
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_config_location }}/traefik/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - custom_rules.yml

- name: Create a volume for letsencrypt
  docker_volume:
    name: data_traefik_letsencrypt

- name: setup traefik docker container
  docker_container:
    name: traefik
    image: traefik:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.traefik }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.traefik }}"
    purge_networks: yes
    command:
      - --global.sendAnonymousUsage
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=web-secure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web-secure.address=:443
      # - --entryPoints.web-secure.http.middlewares=mywhitelist@file
      - --entryPoints.traefik.address=:8080
      - --api=true
      - --api.insecure=true
      - --log=true
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultRule=Host(`{{ '{{' }} .Name {{ '}}' }}.frai.se`)
      - --providers.docker.exposedByDefault=true
      - --providers.docker.swarmMode=false
      - --providers.file.filename=/etc/traefik/custom_rules.yml
      - --providers.file.watch=true
      - --certificatesResolvers.le.acme.email={{ letsencrypt_email }}
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.dnsChallenge.resolvers=molly.ns.cloudflare.com,rudy.ns.cloudflare.com
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "data_traefik_letsencrypt:/letsencrypt"
      - "{{ docker_config_location }}/traefik/custom_rules.yml:/etc/traefik/custom_rules.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      CF_API_EMAIL: "{{ cloudflare_api_email }}"
      CF_API_KEY: "{{ cloudflare_api_token }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
      traefik.http.routers.api.rule: Host(`traefik.frai.se`)
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.certresolver: "le"
      traefik.http.routers.api.service: "api@internal"
