---
# install configarr
# https://configarr.raydak.de/docs/installation/docker

- name: Create a volume for configarr config
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - config_configarr
    - data_configarr

- name: Set ownership on files
  ansible.builtin.file:
    path: /data/docker/docker/volumes/data_configarr/_data/
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"


- name: Copy config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /data/docker/docker/volumes/config_configarr/_data/config.yml
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Setup configarr docker container
  community.docker.docker_container:
    name: configarr
    image: ghcr.io/raydak-labs/configarr:latest
    networks:
      - name: media
    volumes:
      - "config_configarr:/app/config"
      - "data_configarr:/app/repos"
    user: "{{ nobody.user }}:{{ nobody.group }}"
    env:
      TZ: "Etc/UTC"
    state: started
    restart_policy: no
    restart: true
    pull: true
    labels:
      traefik.enable: "false"
