- name: copy configuration files to directory
  copy:
    src: "{{ item }}"
    dest: "{{ docker_config_location }}/homeassistant/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - automations.yaml
    - customize.yaml
  notify: restart homeassistant

- name: copy configuration templates to directory
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_config_location }}/homeassistant/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - configuration.yaml
    - service_account.json
  notify: restart homeassistant
