# setup homeassistant with a docker container
# container from: https://www.home-assistant.io/docs/installation/docker/
---
- name: Create homeassistant config directory
  ansible.builtin.file:
    path: "{{ docker.dir.config }}/homeassistant"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create a volume for homassistant media content
  community.docker.docker_volume:
    name: data_homeassistant_media

- name: Setup homeassistant docker container
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    networks:
      - name: services
        ipv4_address: "{{ docker.networks.services.ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks.services.hosts.ha) \
          | ansible.utils.ipaddr('address') }}"
        ipv6_address: "{{ docker.networks.services.ipam[1].subnet | ansible.utils.ipaddr('network') }}\
          {{ docker.networks.services.hosts.ha }}"
    dns_servers:
      - "{{ dns_servers.adguard.dco.ipv6 }}"
      - "{{ dns_servers.adguard.dco.ip }}"
      - "{{ dns_servers.adguard.home.ipv6 }}"
      - "{{ dns_servers.adguard.home.ip }}"
    volumes:
      - "{{ docker.dir.config }}/homeassistant:/config"
      - "data_homeassistant_media:/media"
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "Europe/Brussels"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.homeassistant.rule: "Host(`ha.frai.se`)"
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.tls.certresolver: "le"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"

- name: Include config tasks
  ansible.builtin.import_tasks: config.yml
  tags: config

- name: Include zwave tasks
  ansible.builtin.import_tasks: zwave.yml
  tags: zwave,zwavejs

- name: Include zigbee tasks
  ansible.builtin.import_tasks: z2m.yml
  tags: zigbee,z2m
