# setup homeassistant with a docker container
# container from: https://www.home-assistant.io/docs/installation/docker/

- name: Create homeassistant config directory
  ansible.builtin.file:
    path: "{{ docker_config_location }}/homeassistant"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create a volume for homassistant media content
  community.docker.docker_volume:
    name: data_homeassistant_media

- name: Setup homeassistant docker container
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    networks:
      - name: macvlan50
        ipv4_address: 172.16.50.65
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.homeassistant }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.homeassistant }}"
    volumes:
      - "{{ docker_config_location }}/homeassistant:/config"
      - "data_homeassistant_media:/media"
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "Europe/Brussels"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.homeassistant.rule: "Host(`ha.frai.se`)"
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.tls.certresolver: "le"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"

- name: Include config tasks
  ansible.builtin.import_tasks: config.yml
  tags: config

- name: Include zwave tasks
  ansible.builtin.import_tasks: zwave.yml
  tags: zwave

- name: Include zigbee tasks
  ansible.builtin.import_tasks: z2m.yml
  tags: zigbee,z2m
