---
- name: Install Postgres
  ansible.builtin.import_tasks: postgres.yml
  become: true

- name: Backup
  ansible.builtin.include_tasks:
    file: backup.yml
    apply:
      tags:
        - never
        - backup
      become: true
  tags: always

- name: Restore
  ansible.builtin.include_tasks:
    file: restore.yml
    apply:
      tags:
        - never
        - restore
      become: true
  tags: always
