# setup unbound with a docker container
# container from: https://github.com/MatthewVance/unbound-docker

- name: setup unbound docker container
  docker_container:
    name: unbound
    image: mvance/unbound:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.unbound }}"
    purge_networks: yes
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.enable: "false"
