- name: Create a volume for plex config
  docker_volume:
    name: config_plex

- name: setup plex docker container
  docker_container:
    name: plex
    image: linuxserver/plex:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.plex }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.plex }}"
    volumes:
      - "config_plex:/config"
      - "/data/media/movies:/movies"
      - "/data/media/series:/series"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      VERSION: "docker"
      # first time only
      # PLEX_CLAIM: claim-54d_4BQ93ykS7m7vmg4X
    devices:
      - /dev/dri:/dev/dri
    state: started
    restart: yes
    restart_policy: always
    pull: true
    labels:
      traefik.http.routers.plex.tls: "true"
      traefik.http.routers.plex.tls.certresolver: "le"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
