---
- name: Create a volume for plex config
  community.docker.docker_volume:
    name: config_plex

- name: Setup plex docker container
  community.docker.docker_container:
    name: plex
    image: linuxserver/plex:latest
    networks:
      - name: media
        ipv4_address: "{{ docker.networks.media.ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks.media.hosts.plex) \
          | ansible.utils.ipaddr('address') }}"
        ipv6_address: "{{ docker.networks.media.ipam[1].subnet | ansible.utils.ipaddr('network') }}\
          {{ docker.networks.media.hosts.plex }}"
    volumes:
      - "config_plex:/config"
      - "/data/media/movies:/movies"
      - "/data/media/series:/series"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
      VERSION: "docker"
      # first time only
      # PLEX_CLAIM: claim-4GowV-_3QSuPH5bpwfvZ
    # devices:
    #   - /dev/dri:/dev/dri
    state: started
    restart: true
    restart_policy: always
    pull: true
    labels:
      traefik.http.routers.plex.tls: "true"
      traefik.http.routers.plex.tls.certresolver: "le"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
