---
- name: Get public ip once
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get public ip
      community.general.ipify_facts:  # generates "ipify_public_ip" var with public ipv4 inside
  tags: always,ipify

- name: Set Cloudflare DNS Records
  hosts: localhost
  gather_facts: false
  connection: ssh
  roles:
    - cloudflare
  tags: cloudflare

- name: Setup ddclient
  hosts: bejbegiavm01
  connection: ssh
  become: true
  roles:
    - ddclient
  tags: ddclient

- name: Setup unbound
  hosts:
    - tag_dns
  connection: ssh
  become: true
  roles:
    - unbound
  tags: unbound

- name: Setup adguard
  hosts:
    - tag_dns
  connection: ssh
  become: true
  roles:
    - adguard
  tags: adguard
