- name: Get public ip once
  hosts: compute,localhost
  gather_facts: false
  tasks:
    - community.general.ipify_facts: # generates "ipify_public_ip" var with public ipv4 inside
  tags: always,ipify

- name: Set Cloudflare DNS Records
  hosts: captain
  connection: ssh
  become: true
  roles:
    - ../roles/cloudflare
  tags: cloudflare

- name: Setup ddclient
  hosts: compute
  connection: ssh
  become: true
  roles:
    - ../roles/ddclient
  tags: ddclient

- name: Setup unbound
  hosts: compute
  connection: ssh
  become: true
  roles:
    - ../roles/unbound
  tags: unbound

- name: Setup adguard
  hosts: compute
  connection: ssh
  become: true
  roles:
    - ../roles/adguard
  tags: adguard
