---
- name: Setup Docker
  hosts:
    - docker
  connection: ssh
  become: true
  roles:
    - docker
  tags: docker

- name: Setup Portainer
  hosts:
    - docker
  connection: ssh
  become: true
  roles:
    - portainer
  tags: portainer

- name: Setup watchtower
  hosts:
    - docker
  connection: ssh
  become: true
  roles:
    - watchtower
  tags: watchtower

