---
- name: Setup Docker, portainer & watchtower
  hosts:
    - docker
  connection: ssh
  become: true
  roles:
    - role: docker
      tags: docker
    - role: portainer
      tags: portainer
    - role: watchtower
      tags: watchtower
