---
- name: Setup hone automation containers
  hosts: BEJBEGIAVM01
  connection: ssh
  become: true
  roles:
    - role: mosquitto
      tags: mqtt,mosquitto
    - role: homeassistant
      tags: homeassistant
