---
- name: Setup Deluge
  hosts: captain
  connection: ssh
  become: true
  roles:
    - role: deluge
      tags: deluge
    - role: jackett
      tags: jackett
    # PLEX
    - role: plex
      tags: plex
    - role: tautulli
      tags: tautulli
    - role: jellyfin
      tags: jellyfin
    # ARR
    - role: radarr
      tags: radarr,arr
    - role: sonarr
      tags: sonarr,arr
    - role: bazarr
      tags: bazarr,arr
    - role: overseerr
      tags: overseerr,overseer,arr
    - role: calibre
      tags: calibre,books
