---
- name: Setup Deluge
  hosts: beokpdcovm01
  connection: ssh
  become: true
  roles:
    - role: deluge
      tags: deluge
    # PLEX
    - role: plex
      tags: plex
    - role: tautulli
      tags: tautulli
    - role: jellyfin
      tags: jellyfin
    # ARR
    - role: sabnzbd
      tags: sabnzbd,arr,usenet
    - role: prowlarr
      tags: prowlarr,arr,trackers
    - role: radarr
      tags: radarr,arr
    - role: sonarr
      tags: sonarr,arr
    - role: bazarr
      tags: bazarr,arr
    - role: overseerr
      tags: overseerr,overseer,arr
    - role: calibre
      tags: calibre,books
