---
- name: Setup redis
  hosts: captain
  connection: ssh
  become: true
  roles:
    - redis
  tags: redis

- name: Setup netbox
  hosts: captain
  connection: ssh
  become: true
  roles:
    - netbox
  tags: netbox
