- name: Setup redis
  hosts: compute
  connection: ssh
  become: true
  roles:
    - ../roles/redis
  tags: redis

- name: Setup netbox
  hosts: compute
  connection: ssh
  become: true
  roles:
    - ../roles/netbox
  tags: netbox
