---
- name: Setup UISP
  hosts: captain
  connection: ssh
  become: true
  roles:
    - uisp
  tags: uisp

- name: Setup unifi
  hosts: captain
  connection: ssh
  become: true
  roles:
    - unifi
  tags: unifi
