# install syncthing docker container
# https://hub.docker.com/r/syncthing/syncthing
---
- name: Create a volume for syncthing content
  community.docker.docker_volume:
    name: config_syncthing

- name: Set permissions to data volume for syncthing
  ansible.builtin.file:
    path: "{{ docker.dir.data }}/docker/volumes/config_syncthing/_data"
    state: directory
    mode: "0755"
    owner: "{{ nobody.user }}"
    group: "{{ nobody.group }}"

- name: Setup Syncthing docker container
  community.docker.docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    networks:
      - name: services
        ipv4_address: "{{ docker.networks.services.ipam[0].subnet \
          | ansible.utils.ipsubnet(24, 0) \
          | ansible.utils.ipaddr(docker.networks.services.hosts.syncthing) \
          | ansible.utils.ipaddr('address') }}"
        ipv6_address: "{{ docker.networks.services.ipam[1].subnet | ansible.utils.ipaddr('network') }}\
          {{ docker.networks.services.hosts.syncthing }}"
    volumes:
      - "config_syncthing:/var/syncthing"
      # - "/data/files:/files"
    env:
      PUID: "{{ nobody.user }}"
      PGID: "{{ nobody.group }}"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.tls.certresolver: "le"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
