# install syncthing docker container
# https://hub.docker.com/r/syncthing/syncthing

- name: Create a volume for syncthing content
  docker_volume:
    name: data_syncthing

- name: setup Syncthing docker container
  docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.syncthing }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.syncthing }}"
    purge_networks: yes
    volumes:
      - "data_syncthing:/var/syncthing"
    env: 
      PGID: "1001"
      PUID: "1001"
    state: started
    restart_policy: always
    restart: yes
    pull: true
    labels:
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.tls.certresolver: "le"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
