# install syncthing docker container
# https://hub.docker.com/r/syncthing/syncthing
---
- name: Create a volume for syncthing content
  community.docker.docker_volume:
    name: config_syncthing

- name: Setup Syncthing docker container
  community.docker.docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker.network.ipv4_prefix }}{{ docker.network.hosts.syncthing }}"
        ipv6_address: "{{ docker.network.ipv6_prefix }}{{ docker.network.hosts.syncthing }}"
    volumes:
      - "config_syncthing:/var/syncthing"
      - "/data/files:/files"
    env:
      PGID: "1001"
      PUID: "1001"
    state: started
    restart_policy: always
    restart: true
    pull: true
    labels:
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.tls.certresolver: "le"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
