---
## ASGARD
- labels:
    site: "Asgard"
    node_name: "CR01_Ironman"
  targets:
    - 172.16.33.1

## MOM
- labels:
    site: "Mom"
    node_name: "CR01"
  targets:
    - 172.16.10.1
- labels:
    site: "Mom"
    node_name: "SW01"
  targets:
    - 172.16.10.2


## DAD
- labels:
    site: "Dad"
    node_name: "CR01"
  targets:
    - 172.16.10.33
- labels:
    site: "Dad"
    node_name: "SW01"
  targets:
    - 172.16.10.34
