- name: Set non proxied a records
  community.general.cloudflare_dns:
    zone: unitix.be
    type: A
    record: "{{ item.name }}"
    value: "{{ item.ipv4 | default(ipify_public_ip) }}"
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
    solo: true
  loop: "{{ domains.unitix.direct }}"

- name: Set non proxied aaaa records
  community.general.cloudflare_dns:
    zone: unitix.be
    type: AAAA
    record: "{{ item.name }}"
    value: "{{ item.ipv6 }}"
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
    solo: true
  loop: "{{ domains.unitix.direct }}"
  when: item.ipv6 is defined

- name: Set non-proxied cname records for gsuite
  community.general.cloudflare_dns:
    zone: unitix.be
    type: CNAME
    record: "{{ item }}"
    value: ghs.googlehosted.com
    proxied: true
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
    solo: true
  with_items:
    - calendar
    - drive
    - mail
    - groups
    - sites

- name: Create TXT records
  community.general.cloudflare_dns:
    zone: unitix.be
    type: TXT
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
  with_items:
    - record: '@'
      value: 'v=spf1 include:_spf.google.com ~all'
    - record: '_dmarc'
      value: "v=DMARC1; p=quarantine; rua=mailto:b61ffcaac5d044d2ad7ed20c29d21822@dmarc-reports.cloudflare.net,mailto\
        :22bfebee@mxtoolbox.dmarc-report.com; ruf=mailto:22bfebee@forensics.dmarc-report.com; fo=1"
    - record: 'google._domainkey'
      value: "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm5XFJf6lwuOoYQw/Bizn1dbAohBdWCEbmiG5kLy448\
        /GVKSF/9mnSg1qLCHNHaAde7ty/pqSTHxhrlSA25NyHWE5f1HvF2EJbOHXivLmnuH9PR/XQS3opJ+NnNkuVl8Cy/glNQ0kfj2DPJtw6Jp8uPvw\
        Ja18cSy3KatNtDviyTEJ9SD7VWuxCW9ggMsq2ksv/gZETB0QCMiB6lHP/V8KjDzD9m5kzn745v39Zv+W4l3GmL3MctpS7DvROgYUT9hny7DP7f\
        Xou79cuoddANzQvm+ppa7BDmIvbFolmMPoZTEpdbkh6yR69jfVB7PwrFYoNui9Ypmg0ydAfVpvl3ZYQwIDAQAB"

- name: Create MX records
  community.general.cloudflare_dns:
    zone: unitix.be
    type: MX
    priority: "{{ item.priority }}"
    value: "{{ item.value }}"
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    state: present
  with_items:
    - priority: 1
      value: 'aspmx.l.google.com'
    - priority: 5
      value: 'alt1.aspmx.l.google.com'
    - priority: 5
      value: 'alt2.aspmx.l.google.com'
    - priority: 10
      value: 'alt3.aspmx.l.google.com'
    - priority: 10
      value: 'alt4.aspmx.l.google.com'
