##### WIREGUARD ON LINUX
# - name: install default packages
#   pacman:
#     name: ['wireguard-tools', 'qrencode']
#     state: latest
#
# - name: copy config files
#   template:
#     src: "{{ item }}.j2"
#     dest: /etc/wireguard/{{ item }}
#     owner: root
#     group: root
#     mode: 0755
#   with_items:
#     - wg0.conf
#     - wgPC.conf
#     - wgLaptop.conf
#     - wgPhone.conf
#     - wgAmelle.conf
#     - wgAmellePhone.conf
#
# - name: restart wg service
#   service:
#     name: "wg-quick@wg0"
#     state: restarted
#     enabled: yes

##### WIREGUARD ON MIKROTIK
## GENERIC DASHBOARDS
- include_tasks:
    file: wg_interfaces.yaml
  loop: "{{ wg_interfaces }}"
  loop_control:
    loop_var: wg_interface
    label: wg_interface.name
  tags: always

# create MTK endpoint config: 
# /interface/wireguard/peers/add allowed-address=172.16.34.0/24 end
# point-address=wireguard.frai.se endpoint-port=2035 comment=ASGARD_CR interface=ASG
# ARD persistent-keepalive=25 public-key="/sO1umhA2iBteRSYY8+xtoI8SHRbdsG3/KblUw5yrX
# k="
# add address to interface