# setup pihole with a docker container
# container from: https://github.com/pi-hole/docker-pi-hole

- name: create pihole config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
  with_items:
    - "{{ docker_config_location }}/pihole"
    - "{{ docker_data_location }}/pihole/dnsmasq/hosts"
    - "{{ docker_data_location }}/pihole/dnsmasq.d"
    - "{{ docker_data_location }}/pihole/lancache"

- name: copy local dns records
  copy:
    src: "{{ item }}"
    dest: "{{ docker_config_location }}/pihole/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - adlists.list

- name: get uklans github repo
  git:
    repo: https://github.com/uklans/cache-domains
    dest: "{{ docker_data_location }}/pihole/lancache/"
    force: yes

- name: copy lancache template files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ docker_data_location }}/pihole/lancache/scripts/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - name: config.json
      mode: "0644"
    - name: copy-files.sh
      mode: "0755"

- name: copy custom domains template file
  template:
    src: 30-custom-domains.conf
    dest: "{{ docker_data_location }}/pihole/dnsmasq.d/30-custom-domains.conf"
    owner: root
    group: root
    mode: 0644

- name: Create new lancache domains at midnight
  ansible.builtin.cron:
    name: "update lancache domains"
    minute: "15"
    hour: "4"
    job: " {{ docker_data_location }}/pihole/lancache/scripts/copy-files.sh"

- name: setup pihole docker container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.pihole }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.pihole }}"
    purge_networks: yes
    volumes:
      - "{{ docker_config_location }}/pihole:/etc/pihole"
      - "{{ docker_data_location }}/pihole/dnsmasq.d:/etc/dnsmasq.d"
      - "{{ docker_data_location }}/pihole/dnsmasq:/etc/dnsmasq"
    env:
      TZ: "Europe/Brussels"
      WEBPASSWORD: "{{ pihole_pass }}"
      VIRTUAL_HOST: pihole.frai.se
      PIHOLE_DNS_: 208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53 #opendns for ecs support
      ServerIP: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.pihole }}"
      ServerIPv6: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.pihole }}"
    restart: yes
    restart_policy: always
    state: started
    labels:
      traefik.http.routers.pihole.tls: "true"
      traefik.http.routers.pihole.tls.certresolver: "le"
      traefik.http.services.pihole.loadbalancer.server.port: "80"
  tags: docker
  vars:
    pihole_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30383662616262326461366563383161346666623538663333343361316334303539613136373130
          3764656632633164393830643133356363386437633836390a653532656634346666656661643936
          66393862356664613337306461313334343365323832303761363539616138326535653135393936
          3435663065636237650a613631656639373663613139316464356466613433396164666135303465
          3063
