# netbox from : https://hub.docker.com/r/linuxserver/netbox

- name: Create a new database with name "netbox"
  community.general.postgresql_db:
    name: netbox
    login_host: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"

- name: create netbox config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "911"
    group: "911"
  with_items:
    - "{{ docker_config_location }}/netbox/"

- name: Start netbox docker container
  docker_container:
    name: netbox
    image: linuxserver/netbox:latest
    networks:
      - name: macvlan333
    volumes:
      - "{{ docker_config_location }}/netbox:/config"
    env:
      ALLOWED_HOST: "netbox.frai.se"
      SUPERUSER_EMAIL: "{{ netbox_superuser_email }}"
      SUPERUSER_PASSWORD: "{{ netbox_superuser_password }}"
      DB_NAME: netbox
      DB_USER: "{{ postgres_user }}"
      DB_PASSWORD: "{{ postgres_password }}"
      DB_HOST: "postgres"
      REDIS_HOST: "redis"
      TZ: "Europe/Brussels"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.netbox.tls: "true"
      traefik.http.routers.netbox.tls.certresolver: "le"
      traefik.http.services.netbox.loadbalancer.server.port: "8000"

# - name: Set prometheus plugin
#   lineinfile:
#     dest: "{{ docker_config_location }}/netbox/configuration.py"
#     state: present
#     regexp: '^PLUGINS = ['
#     line: 'PLUGINS = ["netbox_prometheus_sd"]'
