# netbox from : https://hub.docker.com/r/linuxserver/netbox
---
- name: Get postgres container ip
  community.docker.docker_container_info:
    name: postgres
  register: result_containerip

- name: Create a new database with name "netbox"
  community.general.postgresql_db:
    name: netbox
    login_host: "{{ result_containerip.container.NetworkSettings.Networks.macvlan333.IPAddress }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"

- name: Create netbox config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "911"
    group: "911"
  with_items:
    - "{{ docker.dir.config }}/netbox/"

- name: Start netbox docker container
  community.docker.docker_container:
    name: netbox
    image: linuxserver/netbox:latest
    networks:
      - name: macvlan333
    volumes:
      - "{{ docker.dir.config }}/netbox:/config"
    env:
      ALLOWED_HOST: "netbox.frai.se"
      SUPERUSER_EMAIL: "{{ netbox_superuser_email }}"
      SUPERUSER_PASSWORD: "{{ netbox_superuser_password }}"
      DB_NAME: netbox
      DB_USER: "{{ postgres_user }}"
      DB_PASSWORD: "{{ postgres_password }}"
      DB_HOST: "postgres"
      REDIS_HOST: "redis"
      TZ: "Europe/Brussels"
    restart: true
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.netbox.tls: "true"
      traefik.http.routers.netbox.tls.certresolver: "le"
      traefik.http.services.netbox.loadbalancer.server.port: "8000"

# - name: Set prometheus plugin
#   lineinfile:
#     dest: "{{ docker.dir.config }}/netbox/configuration.py"
#     state: present
#     regexp: '^PLUGINS = ['
#     line: 'PLUGINS = ["netbox_prometheus_sd"]'
