# netbox from : https://hub.docker.com/r/linuxserver/netbox

- name: Create a new database with name "netbox"
  community.general.postgresql_db:
    name: netbox
    login_host: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.postgres }}"
    login_password: "{{ postgres_password }}"
    login_user: "{{ postgres_user }}"

- name: Start netbox docker container
  docker_container:
    name: netbox
    image: linuxserver/netbox:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.netbox }}"
        ipv6_address: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.netbox }}"
    purge_networks: yes
    env:
      ALLOWED_HOST: "netbox.frai.se"
      SUPERUSER_EMAIL: "{{ netbox_superuser_email }}"
      SUPERUSER_PASSWORD: "{{ netbox_superuser_password }}"
      DB_NAME: netbox
      DB_USER: "{{ postgres_user }}"
      DB_PASSWORD: "{{ postgres_password }}"
      DB_HOST: "{{ docker_network.ipv6_prefix }}{{ docker_network.hosts.postgres }}"
      REDIS_HOST: "{{ docker_network.ipv4_prefix }}{{ docker_network.hosts.redis }}"
      TZ: "Europe/Brussels"
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.netbox.tls: "true"
      traefik.http.routers.netbox.tls.certresolver: "le"
      traefik.http.services.netbox.loadbalancer.server.port: "8000"